itapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views 
from itreporting import views as itreporting_views
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('itreporting/', include('itreporting.urls', namespace='itreporting' )),
    path('register/', user_views.register, name = 'register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name= 'profile'),
    path('', itreporting_views.home, name='home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

itreporting/urls.py
from django.urls import path
from . import views
# from .views import PostListView, PostDetailView



app_name = 'itreporting'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('about/',views.about, name= 'about'),
    # path('report/', views.report, name='report'),
    # path('report/', views.PostListView.as_view(), name = 'report'),
    path('issues/', views.PostListView.as_view(), name = 'issue-list'),
    path('issues/<int:pk>', views.PostDetailView.as_view(), name = 'issue-detail'),
    path('issue/new', views.PostCreateView.as_view(), name = 'issue-create'),
    path('issues/<int:pk>/update/', views.PostUpdateView.as_view(), name = 'issue-update'),
    path('issues/<int:pk>/delete/', views.PostDeleteView.as_view(), name = 'issue-delete'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('',views.register, name='register'),
]

itreporting/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse




# Create your models here.

class Issue(models.Model):
    type = models.CharField(max_length=100, choices = [('Hardware', 'Hardware'), ('Software', 'Software')])
    room = models.CharField(max_length=100)
    urgent = models.BooleanField(default = False)
    details = models.TextField()
    date_subimtted = models.DateTimeField(default=timezone.now)
    description = models.TextField()
    author = models.ForeignKey(User, related_name = 'issues', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.type} Issue in {self.room}'
    
    def get_absolute_url(self):

        return reverse('itreporting:issue-detail', kwargs = {'pk': self.pk})

users/models.py
from django.contrib.auth.models import User
from django.db import models

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_pics/profile.jpeg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(label='Email address', help_text='Your SHU email address.')
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username','first_name', 'last_name', 'email']
        

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']
    

itreporting/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Issue


def home(request):
    return render(request, 'itreporting/home.html', {'title': 'Welcome' })

def about(request):
    return render(request, 'itreporting/home.html', {'title': 'Welcome'})

def report(request):
   
    daily_report = {'issues': Issue.objects.all(), 'title': 'Issues Reported'}
    return render(request, 'itreporting/report.html', daily_report)

class PostListView(ListView):
    model = Issue
    ordering = ['date_subimtted']
    template_name = 'itreporting/report.html'
    context_object_name = 'issues'
    paginate_by = 10  # Optional pagination

class PostDetailView(DetailView):
    model = Issue
    template_name = 'itreporting/issue_detail.html'


class PostCreateView(LoginRequiredMixin, CreateView ):
    model = Issue
    template_name = 'itreporting/issue_form.html'
    fields = ['type', 'room', 'urgent', 'details']

    def form_valid(self, form): 
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView): 

    model = Issue
    # template_name = 'itreporting/issue_form.html'
    fields = ['type', 'room', 'details']
    
    def test_func(self):
        issue = self.get_object()
        return self.request.user == issue.author
    
    def handle_no_permission(self):
        messages.warning(self.request, 'You are not allowed to edit this post')
        # return reverse('itreporting:issue-detail', kwargs={'pk': self.kwargs['pk']})
        return HttpResponseRedirect(reverse('itreporting:issue-detail', kwargs={'pk': self.kwargs['pk']}))


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin,DeleteView):
    model = Issue
    success_url = '/itreporting/issues'

    def test_func(self):
        issue = self.get_object()
        return self.request.user == issue.author
    
    def handle_no_permission(self):
        messages.warning(self.request, 'You are not allowed to delete this post')
        # return reverse('itreporting:issue-detail', kwargs={'pk': self.kwargs['pk']})
        return HttpResponseRedirect(reverse('itreporting:issue-detail', kwargs={'pk': self.kwargs['pk']}))

users/views.py
from django.shortcuts import render, redirect
#from django.contrib.auth.forms import UserCreationForm
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Profile



def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f' Your Account created for {username}!, Now you can login')
            return redirect('login') 
        else:
            messages.warning(request, 'Unable to create account.')
    else:
        form = UserRegisterForm()

    return render(request, 'users/register.html', {'form': form, 'title': 'Student Registration'})

@login_required

def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Your account has been successfully updated!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {'u_form': u_form, 'p_form': p_form, 'title': 'Student Profile'}
    return render(request, 'users/profile.html', context)

itreporting/templates/itreporting/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

    <title>Student IT Services - {{title}}</title>
</head>

<body>
    <div class="container">
      <header class="site-header">
          <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
              <div class="container">
                  <a class="navbar-brand mr-4" href="{% url 'itreporting:home' %}">Student IT Services</a>
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                      aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarToggle">
                      <div class="navbar-nav mr-auto">
                          <a class="nav-item nav-link" href="{% url 'itreporting:home' %}">Home</a>
                          <a class="nav-item nav-link" href="{% url 'itreporting:about' %}">About</a>
                          <a class="nav-item nav-link" href="{% url "itreporting:issue-create" %}">Report</a>
                          <a class="nav-item nav-link" href="{% url 'itreporting:issue-list' %}">View Reported Issues</a>
                      </div>
                      <!-- Navbar Right Side -->
                      <div class="navbar-nav"> 

                        {% if user.is_authenticated  %} 
                            <form method="post" id="frm_logout" action="{% url 'logout' %}">
                                {% csrf_token %}
                                <a class="nav-item nav-link" href="javascript:$('#frm_logout').submit();">Logout</a> 
                            </form>
                            <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a> 
                    
                        {% else %}  
                            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a> 
                    
                            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a> 
                        {% endif %} 
                  </div>
              </div>
          </nav>
      </header>
      <div class="row" >

          <div class="col-md-8">
            {% if messages %}
                {% for message in messages  %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
            
            {% block content %}{% endblock %}
          </div>
          <div class="col-md-4" >
              <div class="content-section">
                  <h3>General Information</h3>
                  <p class='text-muted'>Lorem ipsum dolor sit amet, iudico docendi inciderint per eu, ea vis scripta senserit periculis.</p>
                  <ul class="list-group">
                      <li class="list-group-item list-group-item-light">Latest Issues Reported</li>
                      <li class="list-group-item list-group-item-light">IT Policies</li>
                      <li class="list-group-item list-group-item-light">IT Regulations</li>
                      <li class="list-group-item list-group-item-light">Upcoming Events</li>
                  </ul>
              </div>
          </div>
      </div>
  </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

itreporting/templates/itreporting/home.html
{% extends "itreporting/base.html" %}

{% block content %}
    {% if user.is_authenticated  %} 
        <h2>Welcome {{ user.first_name }}  to Student IT Services Homepage</h2>
    {% else %}     
         <h1>Welcome to Student IT Services Homepage</h1>
    {% endif %}
{% endblock %}

itreporting/templates/itreporting/issue_confirm_delete.html
{% extends "itreporting/base.html" %} 

{% block content %} 

<div class="content-section"> 

    <form method="POST"> 

        {% csrf_token %} 

        <fieldset class="form-group"> 

            <legend class="border-bottom mb-4">Delete IT issue</legend> 

          
        </fieldset> 

        <div class="form-group"> 

            <button class="btn btn-outline-danger" type="submit">Delete</button> 
            <a class="btn btn-outline-secondary" href="{% url 'itreporting:issue-detail' object.id %}">Cancel</a>

        </div> 

    </form> 

    </div> 

{% endblock content %} 

itreporting/templates/itreporting/issue_detail.html
{% extends "itreporting/base.html" %}

{% block content %}


        <h1>IT Issues Reported</h1>

        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="#">{{ object.author.profile }}</a>
                    <small class="text-muted">{{ object.date_subimtted }}</small>
                </div>
                <h2 class="article-title">{{ object.type}} Issue in Room {{object.room}}</h2>
                <p class="article-content">{{ object.details }}</p>
                <div class="mt-3">
                    <a href="{% url 'itreporting:issue-update' pk=object.pk %}" class="btn btn-primary mr-2">Edit</a>
                    <a href="{% url 'itreporting:issue-delete' pk=object.pk %}" class="btn btn-danger">Delete</a>
                </div>

            </div>
        </article>

{% endblock content %}

itreporting/templates/itreporting/issue_form.html
{% extends "itreporting/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<div class="content-section"> 
 
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">

            <legend class="borer-bottom mb-4"> Report IT Issue </legend>
            {{ form|crispy }}

        </fieldset>
        <div class="form-group">

            <button class="btn btn-outline-info"  type="submit">Submit</button>
        </div> 

    </form>
    <div class="border-top pt-3">
        <small class="text-muted">Are you already Registered? <a class="ml-2" href="#">Login </a></small>
        
    </div> 
</div>

{% endblock content %}

itreporting/templates/itreporting/report.html
{% extends "itreporting/base.html" %}

{% block content %}

    <h1>Issues Reported</h1>
    {% for issue in issues %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="#">{{ issue.author.profile }}</a>
                    <small class="text-muted">{{ issue.date_subimtted }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'itreporting:issue-detail' pk=issue.id %}">{{ issue }}</a></h2>
                <p class="article-content">{{ issue.details }}</p>
            </div>
        </article>

    {% endfor %}

{% endblock content %}

users/templates/users/login.html
{% extends "itreporting/base.html" %} 

{% load crispy_forms_tags %} 

{% block content %} 

<div class="content-section"> 

    <form method="POST"> 

        {% csrf_token %} 

        <fieldset class="form-group"> 

            <legend class="border-bottom mb-4">Student IT Services - Login</legend> 

            {{ form|crispy}} 

        </fieldset> 

        <div class="form-group"> 

            <button class="btn btn-outline-info" type="submit">Login</button> 

        </div> 

    </form> 

    <div class="border-top pt-3"> 

        <small class="text-muted"> 

        You need to create an account?<a class="ml-2" href="{% url 'login' %}">Login</a> 

        </small> 

    </div> 

</div> 

{% endblock content %} 

users/templates/users/logout.html
{% extends "itreporting/base.html" %} 

{% block content %} 

    <h2>You have now been logged out</h2> 

        <div class="border-top pt-3"> 
            <small class="text-muted"><a class="ml-2" href="{% url 'login' %}">Login</a></small> 
        </div> 

{% endblock content %}

users/templates/users/profile.html
{% extends "itreporting/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="content-section"> 

  <div class="media"> 

   <p><img class="rounded-circle account-img" src="{{user.profile.image.url}}"></p> 

    <div class="media-body"> 

      <h2 class="account-heading">{{user.profile}}</h2> 

      <p class="text-secondary">{{user.first_name}}</p> 

      <p class="text-secondary">{{user.email}}</p> 

    </div> 

  </div> 

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Student IT Services - Profile Details</legend>
        {{ u_form | crispy }} 
        {{ p_form | crispy }} 
    </fieldset>
    <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Update</button>
    </div>
  </form>

</div> 

{% endblock content %}

users/templates/users/register.html
{% extends "itreporting/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Student Registration Form</legend>
            {% comment %} {{ form.as_p }} {% endcomment %}
            {{ form | crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Register</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Registered? <a class="ml-2" href="#">Login</a>
        </small>
    </div>
</div>
{% endblock content %}